# Generated by Django 3.0.5 on 2020-04-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='thumbnail_name',
        ),
    ]
