# Generated by Django 3.0.5 on 2020-04-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200426_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail_name',
            new_name='thumbnail_image',
        ),
    ]
