# Generated by Django 3.0.5 on 2020-04-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200426_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail_image',
            new_name='thumbnailimage',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_name',
            new_name='titlename',
        ),
    ]
